# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt-test/display.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from typing import List

from Qt_ui.utils import generate_pos

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(1500, 960)
        MainWindow.setWindowTitle("Monitor")

        self.num_cam = MainWindow.num_cam
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.videoWin : List[QtWidgets.QLabel] = []
        self.videoLab : List[QtWidgets.QLabel] = []

        pos = generate_pos((1500, 800), self.num_cam)
        for idx, p in enumerate(pos):
            label = QtWidgets.QLabel(self.centralwidget)
            label.setGeometry(QtCore.QRect(p[0], p[1], p[2], p[3]))
            font = QtGui.QFont()
            font.setPointSize(9)
            label.setFont(font)
            label.setMidLineWidth(-1)
            label.setText("")
            label.setPixmap(QtGui.QPixmap("egg.png"))
            label.setScaledContents(True)
            label.setAlignment(QtCore.Qt.AlignCenter)
            label.setObjectName(f"videoWin_{idx}")
            self.videoWin.append(label)


            text = QtWidgets.QLabel(self.centralwidget)
            text.setGeometry(QtCore.QRect(p[0]+p[2]//2-40, p[1]+p[3]+10, 80, 40))
            font = QtGui.QFont()
            font.setFamily("URW Gothic [urw]")
            font.setPointSize(18)
            font.setBold(True)
            font.setWeight(75)
            text.setFont(font)
            text.setObjectName(f"videoLab_{idx}")
            self.videoLab.append(text)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 850, 121, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        setattr(MainWindow, "switch_btn", self.pushButton)

        self.exitbtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitbtn.setGeometry(QtCore.QRect(550, 850, 41, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.exitbtn.setFont(font)
        self.exitbtn.setObjectName("exitbtn")
        setattr(MainWindow, "exit_btn", self.exitbtn)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        for idx, text in enumerate(self.videoLab):
            text.setText(_translate("MainWindow", f"cam{idx+1}"))
        self.pushButton.setText(_translate("MainWindow", "Start-Stop"))
        self.exitbtn.setText(_translate("MainWindow", "EX"))
